import Navigation from '@/components/Navigation';
import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy — MindStash',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      <main className="mx-auto max-w-3xl px-6 pb-24 pt-32">
        {/* Header */}
        <div className="mb-12">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#EA7B7B]/10 px-4 py-1.5 text-sm font-medium text-[#EA7B7B]">
            Legal
          </div>
          <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
          <p className="mt-3 text-gray-500">Last updated: March 18, 2026</p>
        </div>

        <div className="prose prose-gray max-w-none space-y-10 text-gray-700">

          {/* Introduction */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Introduction</h2>
            <p>
              MindStash is operated by Jaydeep Sureliya, an independent software developer based in India.
              Your privacy matters to us. This policy explains what data we collect, how we use it, and
              how we protect it. We keep things simple and transparent because that is what we would want
              as users ourselves.
            </p>
          </section>

          {/* Data Collected */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Data We Collect</h2>
            <p>When you use MindStash, we collect the following:</p>
            <ul className="mt-3 list-disc pl-6 space-y-2">
              <li><strong>Account data</strong> - your email address and hashed password. If you sign in with Google, we receive your Google ID and email. We never store your Google password.</li>
              <li><strong>Content data</strong> - the thoughts, URLs, and notes you capture (limited to 500 characters per item).</li>
              <li><strong>AI metadata</strong> - categories, tags, summaries, priority scores, and urgency flags generated by our AI for your captures.</li>
              <li><strong>Chat history</strong> - messages exchanged with the AI assistant within the app, stored per session.</li>
              <li><strong>Billing data</strong> - your subscription plan, usage counts (items and messages per month), and subscription status. We do not store your credit card details. All payment data is handled by our payment partner.</li>
              <li><strong>Usage data</strong> - basic interaction events (page views, feature usage) used to improve the product. We do not use third-party analytics SDKs or tracking pixels.</li>
            </ul>
          </section>

          {/* How It's Used */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. How We Use Your Data</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>To provide and operate the MindStash service, including AI categorization, chat, and search.</li>
              <li>To process your captures through AI providers for categorization, embedding generation, and surfacing.</li>
              <li>To send you notification reminders, weekly digest emails, and daily briefings you have opted into.</li>
              <li>To enforce plan limits and manage your subscription.</li>
              <li>To improve product quality through anonymized, aggregated usage patterns.</li>
              <li>To respond to your support requests.</li>
            </ul>
            <p className="mt-3">
              We never sell your personal data to third parties. We never use your content to train AI models.
              Your data is only shared with the third-party services listed below, and only to the extent
              necessary to deliver the Service.
            </p>
          </section>

          {/* AI Data Processing */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. AI Data Processing</h2>
            <p>
              MindStash uses AI to power core features. Here is how your data flows through AI providers:
            </p>
            <ul className="mt-3 list-disc pl-6 space-y-2">
              <li>
                <strong>Categorization</strong> - When you capture an item, its content is sent to an AI model to
                determine category, tags, summary, priority, and urgency. This happens once per capture.
              </li>
              <li>
                <strong>Chat</strong> - When you chat with the AI assistant, your messages and relevant context are sent
                to Anthropic&apos;s Claude API to generate responses. Chat history within a session is included for
                context but is not retained by Anthropic beyond the API call.
              </li>
              <li>
                <strong>Embeddings</strong> - For semantic search (Pro plan), item content is converted into vector
                embeddings via OpenAI&apos;s API. The embeddings are stored in our database. OpenAI does not retain the
                input text.
              </li>
            </ul>
            <p className="mt-3">
              Neither Anthropic nor OpenAI uses your data to train their models when accessed via their APIs.
              See their respective privacy policies for details.
            </p>
          </section>

          {/* Third-Party Services */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Third-Party Services</h2>
            <p>MindStash relies on the following sub-processors:</p>
            <ul className="mt-3 list-disc pl-6 space-y-2">
              <li>
                <strong>Anthropic</strong> - Powers the AI chat assistant (Claude API). Subject to{' '}
                <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[#EA7B7B] hover:underline">
                  Anthropic&apos;s Privacy Policy
                </a>.
              </li>
              <li>
                <strong>OpenAI</strong> - Generates vector embeddings for semantic search. Subject to{' '}
                <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-[#EA7B7B] hover:underline">
                  OpenAI&apos;s Privacy Policy
                </a>.
              </li>
              <li>
                <strong>Supabase</strong> - Database provider. Your data is stored in a PostgreSQL database hosted by Supabase in the United States.
              </li>
              <li>
                <strong>Resend</strong> - Sends transactional emails (welcome emails, reminders, digests). Your email address is shared with Resend solely for this purpose.
              </li>
              <li>
                <strong>Vercel</strong> - Hosts the frontend application. Standard request logs apply per Vercel&apos;s policy.
              </li>
              <li>
                <strong>Railway</strong> - Hosts the backend API server.
              </li>
              <li>
                <strong>Lemon Squeezy</strong> - Processes subscription payments. Your email and subscription details are shared with Lemon Squeezy to manage billing. We do not store your credit card information.
              </li>
            </ul>
          </section>

          {/* Data Security */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Data Security</h2>
            <p>We take the security of your data seriously. Here are the measures we have in place:</p>
            <ul className="mt-3 list-disc pl-6 space-y-1">
              <li>Passwords are hashed using bcrypt and never stored in plain text.</li>
              <li>All data is transmitted over HTTPS/TLS encryption.</li>
              <li>API routes are protected with JWT authentication and token refresh mechanisms.</li>
              <li>Database access is restricted to server-side connections only, with connection pooling via Supabase.</li>
              <li>Rate limiting is enforced on all API endpoints to prevent abuse.</li>
              <li>User data is strictly isolated. You can only access your own items, chats, and account data.</li>
            </ul>
            <p className="mt-3">
              No system is perfectly secure. If you discover a security vulnerability, please contact us
              at the email below and we will address it promptly.
            </p>
          </section>

          {/* Data Retention */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Data Retention and Deletion</h2>
            <p>
              Your data is retained for as long as your account is active. Specifically:
            </p>
            <ul className="mt-3 list-disc pl-6 space-y-1">
              <li>You may delete individual items at any time from the dashboard or via the AI chat agent.</li>
              <li>Chat sessions and messages are retained for your reference but can be cleared.</li>
              <li>If you downgrade your plan, your existing data is never deleted. You simply hit lower monthly limits for new captures.</li>
              <li>To request full account deletion, contact us at the email below. We will remove all your data within 30 days.</li>
              <li>Payment event logs are retained for accounting and dispute resolution purposes.</li>
            </ul>
          </section>

          {/* Cookies */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Cookies and Local Storage</h2>
            <p>
              MindStash uses browser local storage to store your authentication token for session management.
              We do not use third-party tracking cookies, advertising pixels, or analytics SDKs.
            </p>
          </section>

          {/* Children */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Children&apos;s Privacy</h2>
            <p>
              MindStash is not intended for users under 16 years of age. We do not knowingly collect data from
              children. If you believe a child has created an account, please contact us and we will delete it.
            </p>
          </section>

          {/* Changes */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. Significant changes will be communicated
              via email. The &quot;Last updated&quot; date at the top of this page reflects the most recent revision.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Contact</h2>
            <p>
              Questions about this policy or your data? Email us at{' '}
              <a href="mailto:privacy@mindstashhq.space" className="text-[#EA7B7B] hover:underline">
                privacy@mindstashhq.space
              </a>.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-8">
        <div className="mx-auto max-w-3xl px-6 flex items-center justify-between text-sm text-gray-400">
          <span>&copy; 2026 MindStash</span>
          <div className="flex items-center gap-6">
            <Link href="/terms" className="hover:text-gray-600 transition-colors">Terms</Link>
            <Link href="/refund" className="hover:text-gray-600 transition-colors">Refund</Link>
            <Link href="/" className="hover:text-gray-600 transition-colors">&larr; Back home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
