import Navigation from '@/components/Navigation';
import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy — MindStash',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      <main className="mx-auto max-w-3xl px-6 pb-24 pt-32">
        {/* Header */}
        <div className="mb-12">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-[#EA7B7B]/10 px-4 py-1.5 text-sm font-medium text-[#EA7B7B]">
            Legal
          </div>
          <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
          <p className="mt-3 text-gray-500">Last updated: March 2026</p>
        </div>

        <div className="prose prose-gray max-w-none space-y-10 text-gray-700">

          {/* Data Collected */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Data We Collect</h2>
            <p>When you use MindStash, we collect the following:</p>
            <ul className="mt-3 list-disc pl-6 space-y-1">
              <li><strong>Account data</strong> — your email address and hashed password.</li>
              <li><strong>Content data</strong> — the thoughts, URLs, and notes you capture.</li>
              <li><strong>AI metadata</strong> — categories, tags, and summaries generated by our AI for your captures.</li>
              <li><strong>Chat history</strong> — messages exchanged with the AI assistant within the app.</li>
              <li><strong>Usage data</strong> — basic interaction events used to improve the product (no third-party analytics SDKs).</li>
            </ul>
          </section>

          {/* How It's Used */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">2. How We Use Your Data</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>To provide and operate the MindStash service.</li>
              <li>To process your captures through AI categorization and surfacing.</li>
              <li>To send you notification reminders and digest emails you have opted into.</li>
              <li>To improve product quality through anonymized, aggregated usage patterns.</li>
            </ul>
            <p className="mt-3">We never sell your personal data to third parties.</p>
          </section>

          {/* Third-Party Services */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Third-Party Services</h2>
            <p>MindStash relies on the following sub-processors:</p>
            <ul className="mt-3 list-disc pl-6 space-y-2">
              <li>
                <strong>Anthropic</strong> — Powers the AI chat assistant. Your chat messages are sent to Anthropic&apos;s API to generate responses.
                Content is subject to{' '}
                <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[#EA7B7B] hover:underline">
                  Anthropic&apos;s Privacy Policy
                </a>.
              </li>
              <li>
                <strong>Supabase</strong> — Our database provider. Your data is stored in a PostgreSQL database hosted by Supabase in the United States.
              </li>
              <li>
                <strong>Resend</strong> — Used to send transactional emails (welcome emails, reminders, digests). Your email address is shared with Resend solely for this purpose.
              </li>
              <li>
                <strong>Vercel</strong> — Hosts the frontend application. Standard request logs apply per Vercel&apos;s policy.
              </li>
              <li>
                <strong>Railway</strong> — Hosts the backend API server.
              </li>
            </ul>
          </section>

          {/* Data Security */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Data Security</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Passwords are hashed using bcrypt and never stored in plain text.</li>
              <li>All data is transmitted over HTTPS/TLS.</li>
              <li>API routes are protected with JWT authentication.</li>
              <li>Database access is restricted to server-side connections only.</li>
            </ul>
            <p className="mt-3">
              No system is perfectly secure. If you discover a security issue, please contact us at the address below.
            </p>
          </section>

          {/* Data Retention */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Data Retention & Deletion</h2>
            <p>
              Your data is retained for as long as your account is active. You may delete individual items at any time from the dashboard.
              To request full account deletion, contact us at the email below and we will remove your data within 30 days.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Contact</h2>
            <p>
              Questions about this policy? Email us at{' '}
              <a href="mailto:privacy@mindstash.app" className="text-[#EA7B7B] hover:underline">
                privacy@mindstash.app
              </a>.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-8">
        <div className="mx-auto max-w-3xl px-6 flex items-center justify-between text-sm text-gray-400">
          <span>© 2026 MindStash</span>
          <div className="flex items-center gap-6">
            <Link href="/terms" className="hover:text-gray-600 transition-colors">Terms</Link>
            <Link href="/refund" className="hover:text-gray-600 transition-colors">Refund</Link>
            <Link href="/" className="hover:text-gray-600 transition-colors">← Back home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
