"""add google oauth fields

Revision ID: a7e3d98ee043
Revises: h8i9j0k1l2m3
Create Date: 2026-03-10 19:58:07.375912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e3d98ee043'
down_revision: Union[str, None] = 'h8i9j0k1l2m3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_content_embedding', table_name='items', postgresql_using='hnsw')
    op.drop_constraint('telegram_links_link_code_key', 'telegram_links', type_='unique')
    op.drop_constraint('telegram_links_telegram_chat_id_key', 'telegram_links', type_='unique')
    op.drop_index('ix_telegram_links_link_code', table_name='telegram_links')
    op.create_index(op.f('ix_telegram_links_link_code'), 'telegram_links', ['link_code'], unique=True)
    op.drop_index('ix_telegram_links_telegram_chat_id', table_name='telegram_links')
    op.create_index(op.f('ix_telegram_links_telegram_chat_id'), 'telegram_links', ['telegram_chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_links_id'), 'telegram_links', ['id'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_telegram_links_id'), table_name='telegram_links')
    op.drop_index(op.f('ix_telegram_links_telegram_chat_id'), table_name='telegram_links')
    op.create_index('ix_telegram_links_telegram_chat_id', 'telegram_links', ['telegram_chat_id'], unique=False)
    op.drop_index(op.f('ix_telegram_links_link_code'), table_name='telegram_links')
    op.create_index('ix_telegram_links_link_code', 'telegram_links', ['link_code'], unique=False)
    op.create_unique_constraint('telegram_links_telegram_chat_id_key', 'telegram_links', ['telegram_chat_id'])
    op.create_unique_constraint('telegram_links_link_code_key', 'telegram_links', ['link_code'])
    op.create_index('ix_items_content_embedding', 'items', ['content_embedding'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
