"""Add AI intelligence signals to items

Revision ID: c9d8f48eedbc
Revises: efe934788a50
Create Date: 2026-01-10 10:30:07.201625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d8f48eedbc'
down_revision: Union[str, None] = 'efe934788a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('intent', sa.String(), nullable=True))
    op.add_column('items', sa.Column('action_required', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('urgency', sa.String(), nullable=True))
    op.add_column('items', sa.Column('time_context', sa.String(), nullable=True))
    op.add_column('items', sa.Column('resurface_strategy', sa.String(), nullable=True))
    op.add_column('items', sa.Column('suggested_bucket', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'suggested_bucket')
    op.drop_column('items', 'resurface_strategy')
    op.drop_column('items', 'time_context')
    op.drop_column('items', 'urgency')
    op.drop_column('items', 'action_required')
    op.drop_column('items', 'intent')
    # ### end Alembic commands ###
