"""Update Item model for 12-category system

Revision ID: efe934788a50
Revises: 5767e0525f9a
Create Date: 2026-01-08 18:56:35.802430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efe934788a50'
down_revision: Union[str, None] = '5767e0525f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(), nullable=True))
    op.add_column('items', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('items', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('items', sa.Column('time_sensitivity', sa.String(), nullable=True))
    op.drop_index('ix_items_ai_category', table_name='items')
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.drop_column('items', 'ai_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('ai_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.create_index('ix_items_ai_category', 'items', ['ai_category'], unique=False)
    op.drop_column('items', 'time_sensitivity')
    op.drop_column('items', 'priority')
    op.drop_column('items', 'confidence')
    op.drop_column('items', 'summary')
    op.drop_column('items', 'tags')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
